export const GET_REQUEST_ROUTINE_LIST_COMPLETED = 'GET_REQUEST_ROUTINE_LIST_COMPLETED';
export const GET_REQUEST_ROUTINE_LIST_ERROR = 'GET_REQUEST_ROUTINE_LIST_ERROR';
export const GET_REQUEST_ROUTINE_LIST_SUCCESS = 'GET_REQUEST_ROUTINE_LIST_SUCCESS';
export const GET_REQUEST_ROUTINE_LIST_START = 'GET_REQUEST_ROUTINE_LIST_START';
