export const INVALIDATED_CARDIO_MACHINE_SESSIONS = 'INVALIDATED_CARDIO_MACHINE_SESSIONS';
export const REQUEST_CARDIO_MACHINE_SESSIONS = 'REQUEST_CARDIO_MACHINE_SESSIONS';
export const RECIEVE_CARDIO_MACHINE_SESSIONS = 'RECIEVE_CARDIO_MACHINE_SESSIONS';
