export const GET_REQUEST_EXERCISE_LIST_COMPLETED =
  'GET_REQUEST_EXERCISE_LIST_COMPLETED';
export const GET_REQUEST_EXERCISE_LIST_ERROR =
  'GET_REQUEST_EXERCISE_LIST_ERROR';
export const GET_REQUEST_EXERCISE_LIST_SUCCESS =
  'GET_REQUEST_EXERCISE_LIST_SUCCESS';
export const GET_REQUEST_EXERCISE_LIST_START =
  'GET_REQUEST_EXERCISE_LIST_START';

export const PUT_REQUEST_EXERCISE_ITEM_CLEAR_SUCCESS_FLAG =
  'PUT_REQUEST_EXERCISE_ITEM_CLEAR_SUCCESS_FLAG';
export const PUT_REQUEST_EXERCISE_ITEM_COMPLETED =
  'PUT_REQUEST_EXERCISE_ITEM_COMPLETED';
export const PUT_REQUEST_EXERCISE_ITEM_ERROR =
  'PUT_REQUEST_EXERCISE_ITEM_ERROR';
export const PUT_REQUEST_EXERCISE_ITEM_SUCCESS =
  'PUT_REQUEST_EXERCISE_ITEM_SUCCESS';
export const PUT_REQUEST_EXERCISE_ITEM_START =
  'PUT_REQUEST_EXERCISE_ITEM_START';
