export const LOADING_EXERCISE_LIST = 'LOADING_EXERCISE_LIST';
export const RECIEVE_EXERCISE_LIST = 'RECIEVE_EXERCISE_LIST';

export const CREATE_NEW_EXERCISE_POST = 'CREATE_NEW_EXERCISE_POST';
export const RECIEVE_NEW_EXERCISE_RESPONSE = 'RECIEVE_NEW_EXERCISE_RESPONSE';
