export const INVALIDATED_CAFFEINE_INTAKE = 'INVALIDATED_CAFFEINE_INTAKE';
export const REQUEST_CAFFEINE_INTAKE = 'REQUEST_CAFFEINE_INTAKE';
export const RECIEVE_CAFFEINE_INTAKE = 'RECIEVE_CAFFEINE_INTAKE';
