export const INVALIDATED_CAFFEINE_INTAKE = 'INVALIDATED_CAFFEINE_INTAKE';
export const REQUEST_CAFFEINE_INTAKE = 'REQUEST_CAFFEINE_INTAKE';
export const RECIEVE_CAFFEINE_INTAKE = 'RECIEVE_CAFFEINE_INTAKE';

export const RECIEVE_CAFFEINE_RESPONSE = 'RECIEVE_CAFFEINE_RESPONSE';
export const RECIEVE_SUCCESSFUL_CAFFEINE_RESPONSE = 'RECIEVE_SUCCESSFUL_CAFFEINE_RESPONSE';
export const SEND_CAFFEINE_POST_REQUEST = 'SEND_CAFFEINE_POST_REQUEST';
