export const GET_REQUEST_NUTRIENTS_REPORTS_COMPLETED =
  'GET_REQUEST_NUTRIENTS_REPORTS_COMPLETED';
export const GET_REQUEST_NUTRIENTS_REPORTS_ERROR =
  'GET_REQUEST_NUTRIENTS_REPORTS_ERROR';
export const GET_REQUEST_NUTRIENTS_REPORTS_SUCCESS =
  'GET_REQUEST_NUTRIENTS_REPORTS_SUCCESS';
export const GET_REQUEST_NUTRIENTS_REPORTS_START =
  'GET_REQUEST_NUTRIENTS_REPORTS_START';

export const GET_REQUEST_NUTRIENTS_TYPES_COMPLETED =
  'GET_REQUEST_NUTRIENTS_TYPES_COMPLETED';
export const GET_REQUEST_NUTRIENTS_TYPES_ERROR =
  'GET_REQUEST_NUTRIENTS_TYPES_ERROR';
export const GET_REQUEST_NUTRIENTS_TYPES_SUCCESS =
  'GET_REQUEST_NUTRIENTS_TYPES_SUCCESS';
export const GET_REQUEST_NUTRIENTS_TYPES_START =
  'GET_REQUEST_NUTRIENTS_TYPES_START';

export const CLEAR_PUT_REQUEST_NUTRIENTS_REPORT_SUCCESS =
  'CLEAR_PUT_REQUEST_NUTRIENTS_REPORT_SUCCESS';
export const PUT_REQUEST_NUTRIENTS_REPORT_COMPLETED =
  'PUT_REQUEST_NUTRIENTS_REPORT_COMPLETED';
export const PUT_REQUEST_NUTRIENTS_REPORT_ERROR =
  'PUT_REQUEST_NUTRIENTS_REPORT_ERROR';
export const PUT_REQUEST_NUTRIENTS_REPORT_SUCCESS =
  'PUT_REQUEST_NUTRIENTS_REPORT_SUCCESS';
export const PUT_REQUEST_NUTRIENTS_REPORT_START =
  'PUT_REQUEST_NUTRIENTS_REPORT_START';

export const CLEAR_PUT_REQUEST_NUTRIENTS_TYPE_SUCCESS =
  'CLEAR_PUT_REQUEST_NUTRIENTS_TYPE_SUCCESS';
export const PUT_REQUEST_NUTRIENTS_TYPE_COMPLETED =
  'PUT_REQUEST_NUTRIENTS_TYPE_COMPLETED';
export const PUT_REQUEST_NUTRIENTS_TYPE_ERROR =
  'PUT_REQUEST_NUTRIENTS_TYPE_ERROR';
export const PUT_REQUEST_NUTRIENTS_TYPE_SUCCESS =
  'PUT_REQUEST_NUTRIENTS_TYPE_SUCCESS';
export const PUT_REQUEST_NUTRIENTS_TYPE_START =
  'PUT_REQUEST_NUTRIENTS_TYPE_START';
