export const GET_REQUEST_NUTRIENTS_LIST_COMPLETED = 'GET_REQUEST_NUTRIENTS_LIST_COMPLETED';
export const GET_REQUEST_NUTRIENTS_LIST_ERROR = 'GET_REQUEST_NUTRIENTS_LIST_ERROR';
export const GET_REQUEST_NUTRIENTS_LIST_SUCCESS = 'GET_REQUEST_NUTRIENTS_LIST_SUCCESS';
export const GET_REQUEST_NUTRIENTS_LIST_START = 'GET_REQUEST_NUTRIENTS_LIST_START';

export const CLEAR_PUT_REQUEST_NUTRIENTS_REPORT_SUCCESS = 'CLEAR_PUT_REQUEST_NUTRIENTS_REPORT_SUCCESS';
export const PUT_REQUEST_NUTRIENTS_REPORT_COMPLETED = 'PUT_REQUEST_NUTRIENTS_REPORT_COMPLETED';
export const PUT_REQUEST_NUTRIENTS_REPORT_ERROR = 'PUT_REQUEST_NUTRIENTS_REPORT_ERROR';
export const PUT_REQUEST_NUTRIENTS_REPORT_SUCCESS = 'PUT_REQUEST_NUTRIENTS_REPORT_SUCCESS';
export const PUT_REQUEST_NUTRIENTS_REPORT_START = 'PUT_REQUEST_NUTRIENTS_REPORT_START';

export const CLEAR_PUT_REQUEST_NUTRIENTS_ITEM_SUCCESS = 'CLEAR_PUT_REQUEST_NUTRIENTS_ITEM_SUCCESS';
export const PUT_REQUEST_NUTRIENTS_ITEM_COMPLETED = 'PUT_REQUEST_NUTRIENTS_ITEM_COMPLETED';
export const PUT_REQUEST_NUTRIENTS_ITEM_ERROR = 'PUT_REQUEST_NUTRIENTS_ITEM_ERROR';
export const PUT_REQUEST_NUTRIENTS_ITEM_SUCCESS = 'PUT_REQUEST_NUTRIENTS_ITEM_SUCCESS';
export const PUT_REQUEST_NUTRIENTS_ITEM_START = 'PUT_REQUEST_NUTRIENTS_ITEM_START';
